name: daily_planner_1
description: "A new Flutter project."
publish_to: ''
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  cupertino_icons: ^1.0.8
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_local_notifications: ^17.2.3
  http: ^1.2.2
  intl: ^0.19.0
  motion_tab_bar: ^2.0.4
  path_provider: ^2.1.4
  provider: ^6.1.2
  quickalert: ^1.1.0
  sqflite: ^2.3.3+1
  table_calendar: ^3.1.2
  workmanager: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/.env
